### ISSUE TITLE
Aufgabenstellung in den Messages

### ISSUE THREAD

**Issue by adriana-1604** [paulina85455/htwd-se-example-teamproject#7]
Wenn im Code etwas aktualisiert wird, könnten wir ja die Aufgabe hinter die Message schreiben, somit weiß jeder auf welche Aufgabe sich die Änderung bezieht.
-- nicht meine Idee, Jeremy hatte das letztens vorgeschlagen  --

**Comment by paulina85455** [comment]
Das ist eine sehr gute Idee!
